### ISSUE TITLE
编译bootctrl报错

### ISSUE THREAD

**Issue by wbs306** [YuKongA/device_xiaomi_rubens-TWRP#4]
编译bootctrl的时候报了这个错误(Note11T Pro) `make: *** kernel/xiaomi/xaga: 没有那个文件或目录。 停止。` 这看着是需要内核的头文件.

我把这行代码去掉后就正常编译通过了
https://github.com/YuKongA/device_xiaomi_rubens-TWRP/blob/d5f5ecd0fee4dd1295615b53caf68e9b73d85507/bootctrl/Android.bp#L29

但是这两台机子都是mt6895, 都没有内核源码, 想问问你们是怎么解决的呢?

**Comment by YuKongA** [comment]
` header_libs: ["generated_kernel_headers"],` 换成这样试试，我们是最新话编译，并且添加了`# Build Hack
BUILD_BROKEN_DUP_RULES := true
`

**Comment by wbs306** [comment]
> ` header_libs: ["generated_kernel_headers"],` 换成这样试试。我们是最小化编译，并且添加了`BUILD_BROKEN_DUP_RULES := true`

感谢，应该是我少了这个配置

**Comment by wbs306** [comment]
刚刚看了一下, 无论是改`header_libs` 还是添加 `BUILD_BROKEN_DUP_RULES := true` 都不行...估计是最小化编译才能通过
